### PR TITLE
Fix/45s - Fix webpack-plugin-serve types

### LINKED ISSUE #45: Typecheck on CI and fix types for webpack-plugin-serve
---

PR #46

---

**About**

We broke the build of the package by accident in c6136aa as the type check fails.

**Possible implementation**

Make sure types are checked by CI and fix the current type error.

### PR DESCRIPTION
**Pull request by bebraw**
---
Closes #45
---

**How to test (feature)**

It should build now. Unfortunately I had to disable webpack-plugin-serve types as they need a bigger update.

**How to test (potential regressions)**

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -7,6 +7,7 @@ import webpack from "webpack";
 import {
   WebpackPluginServe,
   WebpackPluginServeOptions,
+  // @ts-ignore: webpack-plugin-serve types are broken and need an update
```
Comment (TkDodo) [inline src/index.ts]: would it be better to add a `modules.d.ts` somehwere where ts can pick it up and just add:

```
declare module 'webpack-plugin-serve'
```

? This would "stub" everything as "any" and we can remove all `ts-ignores` (they are getting a bit much 😅 ).

if the types are corrected, we can add them, remove the stub and don't have to touch anything else.

**Review by TkDodo — CHANGES_REQUESTED** [review]

File: src/index.ts (hunk 1 above)
Comment (bebraw) [reply src/index.ts]: Sure, I can add a stub as well.

Comment (bebraw) [reply src/index.ts]: I added some kind of a stub for the type to avoid the `ts-ignores`. Once the package type has been fixed, then it can be removed and replaced easily enough.

**Review by TkDodo — APPROVED** [review]
